from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List

from app.database import models, schemas
from app.database.database import get_db
from app.api import deps
from app.core.websockets import manager

from sqlalchemy.orm import selectinload

router = APIRouter(prefix="/payments", tags=["payments"])

@router.get("/", response_model=List[schemas.PaymentResponse])
async def list_payments(
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(deps.require_role([models.UserRole.SUPER_ADMIN, models.UserRole.MANAGER, models.UserRole.CASHIER]))
):
    result = await db.execute(select(models.Payment).order_by(models.Payment.created_at.desc()))
    return result.scalars().all()

@router.post("/", response_model=schemas.PaymentResponse)
async def create_payment(
    payment_in: schemas.PaymentCreate,
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(deps.require_role([models.UserRole.SUPER_ADMIN, models.UserRole.MANAGER, models.UserRole.CASHIER]))
):
    res = await db.execute(select(models.Order).where(models.Order.id == payment_in.order_id))
    order = res.scalars().first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
        
    payment = models.Payment(
        order_id=payment_in.order_id,
        amount=payment_in.amount,
        method=payment_in.method,
        status=models.PaymentStatus.PAID
    )
    db.add(payment)
    
    order.status = models.OrderStatus.CLOSED
    timeline = models.TimelineEvent(
        order_id=order.id,
        description=f"Payment of {payment.amount} collected by {current_user.username}. Order closed."
    )
    db.add(timeline)
    
    if order.table_id:
        table_res = await db.execute(select(models.RestaurantTable).where(models.RestaurantTable.id == order.table_id))
        table = table_res.scalars().first()
        if table:
            table.status = models.TableStatus.AVAILABLE
            await manager.broadcast({
                "type": "TABLE_UPDATED",
                "data": {"id": table.id, "status": table.status, "table_number": table.table_number}
            })
            
    await db.commit()
    await db.refresh(payment)
    
    await manager.broadcast({
        "type": "PAYMENT_COMPLETED",
        "data": {"order_id": order.id, "amount": payment.amount}
    })
    
    return payment

@router.post("/bills", response_model=schemas.BillResponse)
async def create_bill(
    bill_in: schemas.BillCreate,
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(deps.require_role([models.UserRole.SUPER_ADMIN, models.UserRole.MANAGER, models.UserRole.CASHIER]))
):
    res = await db.execute(
        select(models.Order)
        .options(selectinload(models.Order.items))
        .where(models.Order.id == bill_in.order_id)
    )
    order = res.scalars().first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
        
    if order.status != models.OrderStatus.COMPLETED:
        raise HTTPException(status_code=400, detail="Can only generate bills for completed orders")
        
    res_bill = await db.execute(select(models.Bill).where(models.Bill.order_id == bill_in.order_id))
    existing_bill = res_bill.scalars().first()
    if existing_bill:
        return existing_bill
        
    subtotal = order.total_amount
    tax = round(subtotal * 0.10, 2)
    service_fee = round(subtotal * 0.05, 2)
    grand_total = round(subtotal + tax + service_fee, 2)
    
    new_bill = models.Bill(
        order_id=bill_in.order_id,
        subtotal=subtotal,
        tax_amount=tax,
        service_fee=service_fee,
        grand_total=grand_total,
        is_sent=True
    )
    
    db.add(new_bill)
    
    timeline = models.TimelineEvent(
        order_id=order.id,
        description=f"Bill generated by {current_user.username}"
    )
    db.add(timeline)
    
    await db.commit()
    await db.refresh(new_bill)
    
    await manager.broadcast({
        "type": "BILL_GENERATED",
        "data": {
            "id": new_bill.id,
            "order_id": new_bill.order_id,
            "grand_total": new_bill.grand_total
        }
    })
    
    await manager.broadcast({
        "type": "ORDER_BILL_GENERATED",
        "data": {
            "id": order.id,
            "bill_id": new_bill.id,
            "grand_total": new_bill.grand_total
        }
    })
    
    return new_bill

@router.get("/bills/order/{order_id}", response_model=schemas.BillResponse)
async def get_bill_by_order(
    order_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(deps.get_current_active_user)
):
    res = await db.execute(select(models.Bill).where(models.Bill.order_id == order_id))
    bill = res.scalars().first()
    if not bill:
        raise HTTPException(status_code=404, detail="Bill not found for this order")
    return bill

@router.post("/bills/order/{order_id}/send", response_model=schemas.BillResponse)
async def send_bill(
    order_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: models.User = Depends(deps.require_role([models.UserRole.SUPER_ADMIN, models.UserRole.MANAGER, models.UserRole.CASHIER]))
):
    res = await db.execute(select(models.Bill).where(models.Bill.order_id == order_id))
    bill = res.scalars().first()
    if not bill:
        raise HTTPException(status_code=404, detail="Bill not found for this order. Generate the bill first.")
        
    bill.is_sent = True
    
    timeline = models.TimelineEvent(
        order_id=order_id,
        description=f"Bill sent to customer by {current_user.username}"
    )
    db.add(timeline)
    
    await db.commit()
    await db.refresh(bill)
    
    await manager.broadcast({
        "type": "ORDER_BILL_SENT",
        "data": {
            "id": order_id,
            "bill_id": bill.id,
            "grand_total": bill.grand_total
        }
    })
    
    return bill

@router.post("/order/{order_id}/request-counter-payment")
async def request_counter_payment(
    order_id: int,
    db: AsyncSession = Depends(get_db)
):
    from sqlalchemy.orm import selectinload
    res = await db.execute(select(models.Order).options(selectinload(models.Order.table)).where(models.Order.id == order_id))
    order = res.scalars().first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
        
    table_identifier = order.table.table_number if order.table else f"Order #{order.id}"
    
    await manager.broadcast({
        "type": "PAYMENT_REQUESTED",
        "data": {
            "order_id": order_id,
            "table_number": table_identifier,
            "message": f"Customer at {table_identifier} is ready to pay at the counter."
        }
    })
    
    return {"status": "Payment requested"}
